# Generated by Django 2.1.3 on 2019-03-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=100)),
                ('idCard', models.CharField(max_length=100)),
                ('bankCard', models.CharField(max_length=100)),
            ],
        ),
    ]
