# Generated by Django 2.1.3 on 2019-04-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info_update',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('student_pwd', models.CharField(max_length=500)),
                ('home_addr', models.CharField(max_length=300)),
                ('mother', models.CharField(max_length=10)),
                ('mother_phone', models.CharField(max_length=50)),
                ('father', models.CharField(max_length=10)),
                ('father_phone', models.CharField(max_length=50)),
            ],
        ),
    ]
