# Generated by Django 2.1.3 on 2019-04-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0002_user_info_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_account',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('student_pwd', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_info_update',
            name='father',
        ),
        migrations.RemoveField(
            model_name='user_info_update',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='user_info_update',
            name='student_pwd',
        ),
        migrations.AlterField(
            model_name='user_info_update',
            name='student_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
